import './admin-user';
import './profile-edit-profile';
import './profile-edit-password';
import './collection-type';
import './collection-category';
import './collection';
import './journal';
import './config';
import './email-config';
